services:
  nginx:
    build:
      context: requirements/nginx
    container_name: nginx
    restart: always
    volumes:
      - wp-data:/var/www/html
    networks:
      - my_network
    ports:
      - "443:443"
    depends_on:
      - wordpress

  mariadb:
    build:
      context: requirements/mariadb
    container_name: mariadb
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    networks:
      - my_network
    ports:
      - "3306:3306"
    secrets:
      - env

  wordpress:
    build:
      context: requirements/wordpress
    container_name: wordpress
    restart: always
    volumes:
      - wp-data:/var/www/html
    networks:
      - my_network
    secrets:
      - env
    depends_on:
      - mariadb


networks:
  my_network:
    driver: bridge

volumes:
  wp-data:


secrets:
   env:
     file: .env
