services:
  nginx:
    build:
      context: /home/rgreiner/Documents/Inception/srcs/requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - 8080:8080
 # mariadb:
  #  build:
  #    context: /home/rgreiner/Documents/Inception/srcs/requirements/mariadb
   # container_name: mariadb
  #  restart: always
 # wordpress:
 #   build:
  #    context: /home/rgreiner/Documents/Inception/srcs/requirements/wordpress
  #  container_name: wordpress
   # restart: always