services:
  nginx:
    build:
      context: /home/rgreiner/Documents/Inception/srcs/requirements/nginx
    container_name: nginx
    restart: always
    volumes:
      - wp-data:/var/www/html
    networks:
      - my_network
    depends_on:
      - wordpress
  mariadb:
    build:
      context: /home/rgreiner/Documents/Inception/srcs/requirements/mariadb
    container_name: mariadb
    restart: always
    networks:
      - my_network
  wordpress:
    build:
      context: /home/rgreiner/Documents/Inception/srcs/requirements/wordpress
    container_name: wordpress
    restart: always
    volumes:
      - wp-data:/var/www/html
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  wp-data: