services:
  nginx:
    build:
      context: requirements/nginx
    container_name: nginx
    restart: always
    volumes:
      - wp-data:/var/www/html
    networks:
      - my_network
    ports:
      - "443:443"
    depends_on:
      - wordpress
  mariadb:
    build:
      context: requirements/mariadb
    container_name: mariadb
    restart: always
    networks:
      - my_network
    ports:
      - "3306:3306"
    env_file:
      - .env
  wordpress:
    build:
      context: requirements/wordpress
    container_name: wordpress
    restart: always
    volumes:
      - wp-data:/var/www/html
    networks:
      - my_network
    ports:
      - "9000:9000"

networks:
  my_network:
    driver: bridge

volumes:
  wp-data:
